### ISSUE TITLE
Test 01.08.2023

### ISSUE THREAD

**Issue by DanielNowak98** [skunkforce/omniview#10]
Habe das OmniView getestet unter: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

- Auflösung (wahrscheinlich aufgrund meines Systems) der GUI passt sich nicht automatisch an -> Elemente sehr klein.

![Bildschirmfoto vom 2023-08-01 11-01-14](https://github.com/skunkforce/omniview/assets/38864627/80560c74-7e3b-45c6-ae6a-4044220e3c4e)

- Scope wird erkannt. Gemessen werden kann (in meinem Fall)  jedoch nur, sobald ich `sudo ./OmniView` nutze.

![Bildschirmfoto vom 2023-08-01 11-06-45](https://github.com/skunkforce/omniview/assets/38864627/9857b09b-7ed9-432f-b741-e39a2094e30d)

**Comment by dennispelle** [comment]
du kannst die knöpfe jetzt im einstellungsmenü anpassen.
