### ISSUE TITLE
Enhancement: PlotRegion with background

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#104]
Right now the datawindow takes up all the space of the plot region. In the final version the datawindow should be in the middle of the plotregion. This is also shown in the picture below. The background color should be as in the picture. 
![PlotRegion](https://github.com/skunkforce/OmniView/assets/83161524/777b79c5-e0fc-4cb5-a413-dddeadab81d5)

**Comment by R-Abbasi** [comment]
Do you mean the wave in the figure below by the "datawindow", please? 
![Capture2](https://github.com/skunkforce/OmniView/assets/53223982/cd49d9de-9a4b-4347-979b-f34fd56d1bb4)
The background color is also already white just like your figure.

**Comment by AKMaily** [comment]
I am referring to the data window, which is the area where the data, including the entire coordinate system (both the x and y axes as well as the waveform), is displayed. Currently, this data window occupies the entire space of the PlotRegion, resulting in no gap between the sidebarmenu, device list, and the data window. I envision a layout similar to the image I shared, where the data window is situated within the PlotRegion, which serves as the background. Moreover, I'd like the plot region to have a slightly different color than the data window for visual distinction.

**Comment by R-Abbasi** [comment]
How does this look like to you now, please?

![Capture4](https://github.com/skunkforce/OmniView/assets/53223982/22a7492c-1eec-44f3-b221-71157cf9e359)

**Comment by AKMaily** [comment]
This looks good. Can you change the background color of the PlotRegion to a lighter tone?

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/117
