### ISSUE TITLE
Bug: Visibility of the legend

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#105]
The legend in the PlotRegion is to dark. A picture how the legend should look like can be found below. In the legend the names of the devices should be displayed with their corresponding color. 
![legend](https://github.com/skunkforce/OmniView/assets/83161524/c6f4bf99-505a-4835-9343-df80a17463b0)

**Comment by DanielNowak98** [comment]
> If the value is slightly mitigated, all other popup windows in this location are also affected. Personally, I find it easier to read here as well.
> 
> ![grafik](https://private-user-images.githubusercontent.com/38864627/318820381-0d0ac533-50c3-41b1-81a9-810ed7b18d08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjg0NjQsIm5iZiI6MTcxMjA2ODE2NCwicGF0aCI6Ii8zODg2NDYyNy8zMTg4MjAzODEtMGQwYWM1MzMtNTBjMy00MWIxLTgxYTktODEwZWQ3YjE4ZDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MjkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjU4YTNjMDEwZDA3OGQ2YzUwMzJmNTQ1NmZjMmQ3NTQ4NWI3NzE1ZDBmNzg1MGViNTBhMjhkMzhlNDYwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S9zUmUBuj-MVuQ5LdAniD7vadxRwe_meaNmsKhhl3wc)

@AKMaily , what do you think?

**Comment by AKMaily** [comment]
I think we can find a solution for this with the PopColor() and PushColor() functions, so it does not affect every other popupwindow. 
Maybe we can talk about this in tomorrows meeting.

**Comment by DanielNowak98** [comment]
> The issue lies in the fact that the legend color depends on the `PopupBg` color, which is set to this value by default. As seen in the `ImPlot` documentation:
> 
> ![grafik](https://private-user-images.githubusercontent.com/38864627/318813890-eb0c1c07-5dae-4a33-b304-0ef51f93731e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTIyOTksIm5iZiI6MTcxMjE1MTk5OSwicGF0aCI6Ii8zODg2NDYyNy8zMTg4MTM4OTAtZWIwYzFjMDctNWRhZS00YTMzLWIzMDQtMGVmNTFmOTM3MzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWQ0ZGI2MDk0YWNjMWZlZjc2Y2E3MGUwNzZhYzg1YWEzOTgzMGUyMzhiMzMwMWY2MDJkNDExNWNlY2RmYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EsqNJHRV1vWQpN0ownP0niDwsWpaAHZfqocjZ8KvUwk)
> 
> A workaround needs to be developed since ImPlot does not provide an API for it.

Ich habe Style Changes für die Legende hinzugefügt. Die Bezeichnung der einzelnen Scopes ist jedoch durch die Farbänderung nicht/kaum lesbar.
Habe Sie daher vorerst weiss gemacht. Die Farbe lässt sich ja weiterhin ändern.

![grafik](https://github.com/skunkforce/OmniView/assets/38864627/a3e80d47-38fc-4ecd-a5f8-a709c9dae3b8)

**Comment by AKMaily** [comment]
That looks great, do you want to create a PR for this improvements ? @DanielNowak98

**Comment by DanielNowak98** [comment]
#152
