### ISSUE TITLE
Enhancement: Toolbar Region

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#119]
As described in the OmniView-Product Vision document the Software should be seperated into four regions. 

One of these regions is the Toolbar. In this toolbar the save, start and stop button should be placed. 

The first step is to change the position of the buttons and the proportions of the different regions.

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/120

**Comment by AKMaily** [comment]
#120 has four sections. Three of them are implemented like suggested with a few missing style elements. The toolbar region otherwise does not have the buttons that were suggested and the icons are not yet implemented. I am already working on a version in which this is implemented.

**Comment by R-Abbasi** [comment]
> In this toolbar the save, start and stop button should be placed.

The toolbar region/`ImGui::BeginChild` is, to me, the top one on the right side `ImGui::BeginChild` which has the above buttons.

**Comment by AKMaily** [comment]
Yes it is the top one on the right side, but it only has this buttons at the left side and with a string as the description. Those will be replaced by Icons and should be placed in the middle.
