### ISSUE TITLE
Feature : Loading old data 

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#155]
To display old measurements, the user should be able to load already saved .csv Files from their file browser into the Software and display them in the plot region. This includes the following steps: 

1. Having a menu or button that opens the file browser where the data can be displayed 
2. Displaying the filenames in the "Devices connected" section
3. Selecting which data should be displayed in the plot region 
4. Displaying the data in the plot region 

First it should be researched how the data can be loaded into the Software and displayed in the plot region. A cods example should be provided.

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/156
