### ISSUE TITLE
Feature: Loading old data. Concrete description

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#157]
To be able to display previously recorded and saved measurements, the user must have the capability to access these within the software. For this purpose, the following user flow has been designed: Between the "Search Devices" button and the "Diagnose" button, an additional button labeled "Load Old Data" is added. When this button is pressed, a menu opens. This menu contains multiple input fields stacked vertically, with one by default, but more can be added using an adjacent "+" button. Each input field has a "Browse" button next to it, which opens the file browser when clicked. From the file browser, the user can load an old .csv file. If the user selects a file that is not a .csv, a popup window with the message "Incorrect file format" will appear. After selecting the file, its path will appear in the input field. The user can also manually type a path into the input field, but this path must also end with .csv. Once the user has entered all the paths, they can click the "Load All Data" button at the end of the menu window or the back button. When the user clicks the "Load All Data" button, all the .csv files they have entered will be loaded and displayed in the "Found Devices" section. Here, the user can select the dataset to be displayed in the plot window by using a checkbox located to the left of each dataset. Multiple datasets can be displayed simultaneously. If additional devices are connected and displayed, their measurement data should also continue to be shown in the plot window.

**Comment by R-Abbasi** [comment]
Does the _Load Old Data_ button need an icon like _Search Devices_ and _Diagnose_ buttons, please?

**Comment by AKMaily** [comment]
Yes it does, we will design this logo next week.

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/156 (after refinements, changes and improvements) is meant to address the first step. 
Here's a screenshot of comparing data from loading a file (in black) and live from a generator (in green):
![1](https://github.com/skunkforce/OmniView/assets/53223982/00db1610-2380-453d-ae7e-e0f335ad3cc2)
