### ISSUE TITLE
Bug: Saving synchronized data from more than one device 

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#169]
# Description: 

Measuring a waveform with two or more devices.  Saving all of those measurements via the saving popup results in the same amount of files as devices were selected.

Bug: Those files have different sizes therefore not the same amount of data points. 

## Problem: 

The OmnAIScopes are synchronized. Therefore when starting a measurement the OmnAIScopes start measuring at the same timestamp. They also stop at the same timestamp. As the sampling rate of both devices is the same, the same amount of data points is measured. For each device one file is created. As they both have the same amount of data points, if all data points that were measured are saved correctly the files will have the same size and the same amount of data points.  

## Case: 

All datapoints are positive and between a range of 20  to 50 on the y-axis.

## Reproducing the bug: 

Connect two Scopes with USB-C cables to a Hub. Connect this Hub to the laptop. The Scopes are not connected to a voltage source.

Open the software. 

### Press the Buttons: 

Search for devices --> Start (Play symbol button) --> Stop (stop symbol button) --> Save (Save symbol button)

In the opening Popup menu, open the section "Deviceslist(/Geräteliste)" 

Select two devices in the drop-down menu --> Press Save (Speichern)

![image](https://github.com/skunkforce/OmniView/assets/83161524/ad6d3da4-a2b8-4e77-a8be-2bf61828af24)

Go into the direction where the Application is saved. 

Look in the build/Release/saves/ folder. Here the files should be saved. You should see that both files have a different size.

![image](https://github.com/skunkforce/OmniView/assets/83161524/5cff7d82-4666-44a0-9ed5-0dc8ccd5f9ef)

### Files that were created when testing, the second file is always smaller than the first: 

[device1-2024-07-04T09-59.csv](https://github.com/user-attachments/files/16096933/device1-2024-07-04T09-59.csv)
data points: 81337
[device2-2024-07-04T09-59.csv](https://github.com/user-attachments/files/16096935/device2-2024-07-04T09-59.csv)
data points: 67427

### Userflow: 

--> Measuring a waveform with two or more devices , waveform in range 20  to 50 on the y-axis.
--> Pressing the save button 
--> Selecting all devices in the drop down menu 
--> Pressing save 

### Output: 

- The same amount of files as devices where selected
- every file has the same amount of data 
- every file only saves the data from their corresponding specific device 

 
## Test that should work if the files are saved correctly 

Connecting two / three / four devices that are not connected to a voltage source. 

--> press the start button 
--> press the stop button 

Expected image : 

![image](https://github.com/skunkforce/OmniView/assets/83161524/20128ef1-6318-4c37-b8ac-a8dac38a8c19)

--> Press the save button 
--> select one device 

Expected image: 

![image](https://github.com/skunkforce/OmniView/assets/83161524/e0f23dfb-b11b-4c4a-a59b-4ea4b4ef762d)

--> Press save 

Expected output: 

![image](https://github.com/skunkforce/OmniView/assets/83161524/47e5b8de-43ad-4d2c-88c3-476466eb9ca1)

The file should contain every measured data point from the measurement from the selected device.

--> Go back to the application 
--> Press the save button again 
--> select all connected devices 

Expected image : 

![image](https://github.com/skunkforce/OmniView/assets/83161524/d20cddaf-1f2e-4ae2-904a-3a0044a9ef3c)

--> Press save 

Expected output for two devices: 

![image](https://github.com/skunkforce/OmniView/assets/83161524/d4c7151b-eee4-45b3-9227-98f8cef83734)

All files that are saved should contain the datapoints of their corresponding device. The files should all have the same size, as the same amount of datapoints was measured by each device. 

This should work for connecting one or more devices up to 256. 

## Definition of done: 

--> All described tests are fulfilled
--> All variable_names in the new code describe what the purpose of the variable
--> The new code fulfills the c++ standard
--> The new code fulfills the code standard for this project
--> All files that were changed are formatted with the given clang-format 

If there are any questions regarding this issue feel free to ask in the comments of the issue.

**Comment by R-Abbasi** [comment]
Which version of the software did result in files with different sizes as shown in the **Reproducing the bug** section above, please?

**Comment by AKMaily** [comment]
The current master version : d0edbc2

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/167
The branch above works based on [this](https://github.com/skunkforce/OmniView/pull/167#issuecomment-2191213881) and [this](https://github.com/skunkforce/OmniView/pull/167#issuecomment-2199469488)  tests for the specifications above.
