### ISSUE TITLE
Feature: Installer for the Application

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#170]
# Description 

As the OmnAIScope is going in the first prerelease phase customers should be able to download the software onto their device. 

To make this as simple as possible for the user the OmnAIView software should be installed on the customer PC via an installer. 

## Goal 

The goal is to have a shortcut of the Software via this icon on the customers desktop as well as a folder /OmnAIView/ on the customers desktop where the software an its components are. 

![image](https://github.com/skunkforce/OmniView/assets/83161524/31ae0ad1-d1d8-47bd-b8fe-badfc234d9df)

A picture of the icon that should be used. 

## Userflow 

The User will be navigated from the shop after buying the device to a download website. On this download website there are two buttons: download for windows and download for linux. 
This website already exists. 

![image](https://github.com/skunkforce/OmniView/assets/83161524/a00fa1b0-6811-454b-a21c-ead4faa8c3ee)

When pressing on one of the buttons the corresponding installer should be downloaded, like this : 

![image](https://github.com/skunkforce/OmniView/assets/83161524/d70b0c90-443e-461a-8f22-1676ae18ad00)

Clicking on the installer the installation should start. 

When the installation is done the client has the software on their PC in the given directory as well as a shortcut with the given icon on their desktop. Clicking on the icon should open the software. 

Definition of done: 

- The client can download an installer via the download website. 
- The installer will install the OmnAIView software with its corresponding folders (config) in a given directory
- A shortcut on the client computer exists to the Software 
- Clicking on the icon will start the software in the correct way 

Please feel free to ask question about this issue in the comments.

**Comment by R-Abbasi** [comment]
Properties for the Windows setup file [OmniView_Setup.zip](https://github.com/user-attachments/files/16158685/OmniView_Setup.zip): 
- Product Name: **OmniView**
- Product Version: **0.9.0+3fbcd21**
- Company Name: **Auto-Intern** 
- Website URL: **https://www.auto-intern.de/**
- Supported OSes: **Windows 7, 8, 10, 11, server 2016, 2019, 2022**
- Header Image for the setup wizard 
- Support many languages 
- Visit website after uninstallation
- Custom icon for the setup, shortcuts and uninstaller files 
- License Agreement text: _Read this license agreement before using the OmniView product._

Run it as administrator

![1](https://github.com/skunkforce/OmniView/assets/53223982/4542182d-c592-44e1-bcf2-a9db4db18d17)

**Comment by AKMaily** [comment]
I downloaded the .zip and clicked on the OmniView-Setup in the .zip folder. I went through the installation process and had the Icon on Desktop checked, but i got no Icon on my Desktop.

**Comment by R-Abbasi** [comment]
That sounds a little odd. 
Just did the same: _Download that zip file -> unzip it > run the setup -> use the German language_. It created a shortcut on Desktop and worked fine. It's possible to show it in a `.gif` file too, if needed.

**Comment by AKMaily** [comment]
The user should only click on the installer to download the programm and not need to unzip the file.

**Comment by R-Abbasi** [comment]
As stated in the **Userflow** section, the user downloads the installer from the website and runs it to install the program on their device.
`.zip` was used to upload the file here merely. The `.exe` file inside it can be used on the website.

**Comment by AKMaily** [comment]
![image](https://github.com/skunkforce/OmniView/assets/83161524/2bd54555-0b03-421d-9f85-13b2a5942e44)

My system thinks the .zip could be a virus. Do you know how this can happen and how i can change it, so that is can download the .zip again? The first time it worked.

**Comment by R-Abbasi** [comment]
Sometimes Windows complains about files when the publisher is not well known to it. `.zip` is only for here, the GitHub website, as it doesn't support `.exe` files to be uploaded. 
You can disable your anti virus temporarily and unzip the file on you system, I guess.

**Comment by AKMaily** [comment]
I am not able to reproduce this, please upload a video of the process. 

> That sounds a little odd. Just did the same: _Download that zip file -> unzip it > run the setup -> use the German language_. It created a shortcut on Desktop and worked fine. It's possible to show it in a `.gif` file too, if needed.

**Comment by R-Abbasi** [comment]
![OmniGif2](https://github.com/skunkforce/OmniView/assets/53223982/a1934073-4242-4288-94d7-3a6467837df9)

**Comment by AKMaily** [comment]
Okay i tried to reproduce this userflow, i also get a shortcut on my PC but without the Icon: 
![image](https://github.com/skunkforce/OmniView/assets/83161524/17391486-d170-4e52-b34e-194960f6627c)

**Comment by R-Abbasi** [comment]
Here's a new version [OmniView.zip](https://github.com/user-attachments/files/16189710/OmniView.zip)
Tested it on a virtual device as well and it created shortcuts with icons on that too. 
![1](https://github.com/user-attachments/assets/0194e162-7881-403c-ad83-0d82db2bf2a3)

**Comment by AKMaily** [comment]
The .exe was added to the release folder.
