### ISSUE TITLE
Bug: Old Files with calibrated data are not shown in the Plot Region

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#176]
Issue: Files with calibrated data that are loaded into the software are not shown in the Plot Region. 

Reproduction: Measuring with a calibrated device, saving the data, click on "Load old Data" and checking the box for the old data: 

![image](https://github.com/user-attachments/assets/96f557d8-ac94-41c3-bd8e-6a253bbe30c5)

I currently dont know if the data is not shown at all or if it is shown in a wrong place. 

Definition of Done: 

Data of a loaded file should be shown as it was before in the Plot Region : 

![image](https://github.com/user-attachments/assets/de072007-9413-4ced-ae5f-a5a5ad000c5f)

**Comment by R-Abbasi** [comment]
Yes, as told you, it certainly does.

Found the source of the issue and need to get what was meant to be done by the code then fix the bug.

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/177
