### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by markuskae** [skunkforce/OmniView#29]
LED blinkt, wenn Messung gestoppt wird weiter.

Wenn das Gerät gefunden wird, leuchtet die LED durchgehend. Beim Start einer Messung fängt sie an zu blinken, hört jedoch nicht wieder auf.

**Comment by NP199** [comment]
The LED isnt resetted either, when a measurement is done and saved and reseted

**Comment by AKMaily** [comment]
This issue has been fixed in the current version
