### ISSUE TITLE
Screen size does not adjust to display size

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#38]
![Screenshot_2023-10-20_16-39-20](https://github.com/skunkforce/omniview/assets/83161524/24539e65-be43-4f86-8e61-4681d3f4872b)

If opened on Linux-System (Debian GNU/Linux 12 (bookworm)) the size of the program window adapts to the screen size but the size of the displayed program doesn't, so parts of the program aren't visible.  

Version: commit 6645bba5c9069d0ac80439ca67fa6fcfaaa97782

**Comment by NP199** [comment]
Yes the window size is hard coded at the moment.
This should be changed. The reason it isn`t implemented yet, is that it was a little bit problematic to get a function to return the right work area size of the monitor.

**Comment by bjoekeldude** [comment]
This funktion is depending on whether DWM (Windows), X11 or Wayland (both Linux) is utilized. I guess ImGui is using X11 in our example, @NP199?

Potential solutions:
Windows solution:
```
#include <windows.h>
int screenWidth = GetSystemMetrics(SM_CXSCREEN);
int screenHeight = GetSystemMetrics(SM_CYSCREEN);
```

X11 solution:
```
#include <X11/Xlib.h>
Display* display = XOpenDisplay(NULL);
int screenWidth = DisplayWidth(display, DefaultScreen(display));
int screenHeight = DisplayHeight(display, DefaultScreen(display));
XCloseDisplay(display);
```

Wayland solution:
```
#include <gtk/gtk.h>
gtk_init(&argc, &argv);
GdkScreen* screen = gdk_screen_get_default();
int screenWidth = gdk_screen_get_width(screen);
int screenHeight = gdk_screen_get_height(screen);
```

No guarantees. I am just spitballing here.
We should then decide at compile-time which implementation shall be used.
@dominicpoeschko do you agree?

**Comment by NP199** [comment]
The problem is not getting the right screen size. It is getting the proper working area. Sometimes you have toolbars (i think in windows the taskbar) and they would be overlapped with the window from omniview. The function for glw to get the working area did not work properly, but maybe i used it the wrong way

**Comment by bjoekeldude** [comment]
I see. 
One approach to resolve this issue would be to maximize the window right after creation, then getting the window size and rerendering everything.

**Comment by AKMaily** [comment]
For devices with more than 1280x760 pixels this works fine now.
