### ISSUE TITLE
Compilation-Errors on Linux 

### ISSUE THREAD

**Issue by bjoekeldude** [skunkforce/omniview#39]
When compiling OmniView on Linux, I've encountered several issues during the cmake process. Given the less than ideal developer experience, I'm considering whether it would be beneficial to include the necessary prerequisites in the README.md file. These prerequisites could be listed as follows:
```
apt install build-essential autoconf gtk-doc-tools libtool intltool curl zip unzip tar libudev-dev
```
This would help streamline the setup process for other developers and potentially reduce the number of issues encountered during the compilation process.

**Comment by rkta** [comment]
Sounds good to me, but keep in mind that apt only works for some distros.
