### ISSUE TITLE
Feature Request: Automatically Capitalize VIN Input

### ISSUE THREAD

**Issue by markuskae** [skunkforce/OmniView#46]
It would be perfect, if the VIN will be written in capital letter automatically.

**Comment by bjoekeldude** [comment]
In order to do this, there should be a diagram of the the actual steps, that one performs to make a complete measurement set. 

Is there a video, that documents the process on the the users PC?
If so, please post in this issue.

**Comment by AKMaily** [comment]
This has been fixed with the latest version.
