### ISSUE TITLE
Update Software Title When Releasing a New Version

### ISSUE THREAD

**Issue by markuskae** [skunkforce/omniview#51]
Currently, we have two versions of the software with the same title. This creates confusion for our users. We need to ensure that the software title is updated every time a new version is released.

Old Version:
![image](https://github.com/skunkforce/omniview/assets/115779152/c284ee7a-f9e7-402d-9ca6-929d6a1f18d6)

New Version:
![image](https://github.com/skunkforce/omniview/assets/115779152/474b56e0-d410-4fdb-819e-2075712c6dd4)

**Comment by bjoekeldude** [comment]
duplicate of #50
