### ISSUE TITLE
Adjusting scales

### ISSUE THREAD

**Issue by bjoekeldude** [skunkforce/OmniView#61]
As of now, the X- and Y-axis are labeled as samples in X and counts in Y axis. 
The X-axis should be written in seconds, while the Y-axis should display volts. Currently OmniView is only supporting one type of input device - the AI OmniScope. Each Device comes with a fixed sample rate and two individual calibration-values: offset and scaling. In the near furture @NP199 will make sure, that these informations can be read from the device itself. Until then, we will use one set of fixed values that should be read from the config-file. 
```
{
    "calibration":{
             "samples_per_second": 50000,
             "counts_offset": 45,
             "counts_per_volt": 100
     }
}
```
Even though these values don't make sense at the moment, they shall be used to scale the X- and Y-axis.

**Comment by R-Abbasi** [comment]
![Capture](https://github.com/skunkforce/omniview/assets/53223982/0f5ec022-25d0-4c0e-b49f-a2b4283621b1)
 x and y axes ranges are [0, 10], [-10, 200] respectively, with specific values/ticks on Y-axis
 
 Will try to change/enhance it if needed.

**Comment by AKMaily** [comment]
As it is implemented in the software and the calibration will be implemented in the next week, this issue will be closed.
