### ISSUE TITLE
Programm crash after second measurement 

### ISSUE THREAD

**Issue by AKMaily** [skunkforce/OmniView#75]
When clicking on 'Search for devices' after the initial measurement has been reset, the window closes, and the program crashes.

**Comment by NP199** [comment]
I cant reproduce this error when pressing "Search for devices". 
I have an error when saving the measurement, the window closes and the programm crashes.

**Comment by AKMaily** [comment]
1.  Did you record a measurement, reset it and then try to record again? This has already crashed on two PCs.
  2.  Did you get an error message when the programm crashes ?

________________________________
Von: Niklas Pierick ***@***.***>
Gesendet: Mittwoch, 20. Dezember 2023 17:39
An: skunkforce/OmniView ***@***.***>
Cc: AKMaily ***@***.***>; Author ***@***.***>
Betreff: Re: [skunkforce/OmniView] Programm crash after second measurement (Issue #75)


I cant reproduce this error when pressing "Search for devices".
I have an error when saving the measurement, the window closes and the programm crashes.

**Comment by NP199** [comment]
Yes i tried reproducing the error, as you wrote it down. I resetted the thing mutliple times and used both functions. I had only problems when using the save function.
I used the githash version [ec38fa6]



My colleague used the githash version [0836b9b] (https://github.com/skunkforce/OmniView/commit/0836b9b19051e04c5ca148a99dc150090d91e5a7) yesterday and had no problems with searching and saving the files.

I got no error messages

**Comment by AKMaily** [comment]
Did you use the windows or the linux version?

**Comment by NP199** [comment]
My colleague and myself both used the windows version

**Comment by AKMaily** [comment]
Did you connect one or two devices to the pc?

**Comment by AKMaily** [comment]
This issue has been fixed with Pull Request #91.
