### ISSUE TITLE
Refactoring files in OmniView/src

### ISSUE THREAD

**Issue by R-Abbasi** [skunkforce/OmniView#92]
A suggestion to refactor files in _OmniView/src_, enhance the readability and make future maintenance more straightforward/easier:
- create two libraries (more preferably using `#ifndef ...` and not `#pragma once` include guards) managing related parts of the whole functionality this way: `popups.hpp` as the interface for: `settingspopup`, `saves_popup`, `look_up_saves` and `create_training_data`, and `handler.hpp` as the interface for: `apihandler`, `get_from_gthub`, `jasonhandler` and `sendData`. That is, two interfaces with 8 implementations (`.cpp` files) and `include` those two libraries in `main.cpp` instead of 8 header-only libraries. This way, we can get rid of header-only libraries and their disadvantages (look it up or [read this, for example](https://stackoverflow.com/a/12673877/4989541)).

- It is also possible to simplify `main.cpp` by taking part of its code into `handler.hpp` and declare the needed function(s) there.

**Comment by NP199** [comment]
Great suggestion.
I don`t understand the reason to use #ifndef ... over pragma once. Can you elaborate on this?

What do you think about the use of designated namespaces in the libraries?

**Comment by R-Abbasi** [comment]
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf8-use-include-guards-for-all-header-files:
_Some implementations offer vendor extensions like #pragma once as alternative to include guards. It is not standard and it is not portable. It injects the hosting machine’s filesystem semantics into your program, in addition to locking you down to a vendor._ So, I assume using `#ifndef ...` might be a better choice.

Namespaces as a mechanism for expressing that some declarations belong together and that their names shouldn’t clash with other names sound harmless but considering the libraries I've worked on (_OmniView/src_, `imfilebrowser.h` and part of _/OmniView/ai_omniscope-v2-communication_sw/src_), using namespaces looks to be for that reason or an approach to make the provided features seem as if they're built-in `ImGui` ones, e.g., `ImGui::FileBrowser` in `imfilebrowser.h`. In `main.cpp`, however, using that namespace doesn't make much sense to me. 
Anything you like to add/modify, please?

**Comment by R-Abbasi** [comment]
Namespaces are generally beneficial merely in external libraries, on the one hand. Shared libraries don't use namespaces normally, so this increases the probability of name conflicts with the project, on the other hand. But typically a prefix is added to the symbol names as a form of namespace, e.g., `SDL` with `SDL_`. `glfw`, `glad`, and even big APIs like `OpenGL` and `Vulkan` apparently do this as well.
Hence, I personally don't suppose we need to declare any namespace in the project.

**Comment by AKMaily** [comment]
How would you then incorporate functions for the plot regions that perform the same task but have different implementations for various plot regions, such as differences in style or button size, into the program without causing namespace collisions?

**Comment by R-Abbasi** [comment]
The usual construct is "name collisions" and is not relevant to the tasks the functions perform, but more to their signatures, I suppose.
Namespace names are unique. However, they can be re-opened if required.
